### ISSUE TITLE
Script will also change the review dates of dropped or completed items

### ISSUE THREAD

**Issue by rpapallas** [joebuhlig/OFScripts#10]
Hi Joe,

Your script is a masterpiece and the idea behind it is very powerful! Thanks for opening the source code and sharing your effort. I think this script is what I was looking for. I have a minor feedback to make if you wish:

I ran the script for first time and it took very long, so I inspected the "Changed" perspective to see what changes have been made. Surprisingly I saw that the script also went through and updated the next review dates of the "Completed" projects (I think and for Dropped, but I have now Moved old data to archive and I can't verify). I think the script needs to handle this case. Is there a personal use case for this behaviour that I can't think at the moment?

I think this case check (checking if the project is not completed or dropped) will boost the run time of the script especially for users that don't run the "Move old data to archive". Nevertheless, it was a great reminder to do archiving of my old data in OmniFocus 😄

Regards,
Rafael

**Comment by joebuhlig** [comment]
I never noticed it running on Completed or Dropped projects. But I added a check for Active or On Hold projects only. Seems to run quicker this way too. Nice catch!

https://github.com/joebuhlig/OFScripts/commit/7b6798edff932ab9d4155b947f6c8666efb0d950
