### ISSUE TITLE
You have an OmniFocus folder but you don't specify where

### ISSUE THREAD

**Issue by ghost** [joebuhlig/OFScripts#11]
In your photo you have the rule set to an OmniFocus folder but it doesn't make sense to me. Where is the script pulling this information from? `if name is OmniFocus`.  Where is it looking for this? It's not exactly clear.

I've run the script and nothing happens, no task report. What am I missing?

**Comment by joebuhlig** [comment]
Good call. I was certain this was in there but even I don't see it. 

The folder I have Hazel running on is here: `/Users/YOURUSER/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Application Support/OmniFocus`
