### ISSUE TITLE
Can’t get curDate's day. Access not allowed. (-1723)

### ISSUE THREAD

**Issue by ghost** [joebuhlig/OFScripts#2]
Hey there,

I kept running up against the following error when trying to run the Applescript using Omnifocus:

"The script “UpdateReviews.applescript” could not complete.

AppleScript reported the following error:

The operation couldn’t be completed. /Users/charlesmagnuson/Library/Application Scripts/com.omnigroup.OmniFocus2.MacAppStore/UpdateReviews.applescript:4176:4189: script error: Can’t get curDate's day. Access not allowed. (-1723)"

Turns out that Omnifocus cannot run Applescripts. After I imported the script script it ran just fine in Omnifocus. There probably won't be too many noobs like myself using this script you created, but I wanted to note that this kind of point could use clarification in future read me files.

Thanks for the wonderful script!

-Charles

**Comment by joebuhlig** [comment]
I really thought I had a section describing this on the main page. I'm sorry, Charles. I'll be making the update today.

**Comment by joebuhlig** [comment]
I updated the Readme for each script (and the main) to reflect this.

**Comment by ghost** [comment]
Thank you so much for the quick reaction, Joe! I am loving your OmniFocus and productivity resources. Just sent you a donation to show my appreciation.
