### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by svsmailus** [joebuhlig/OFScripts#4]
#DailyTaskReport
I've installed the script added the relevant rule in hazel, but all I get is a text file with:

`# Day, Date`

The rest is blank. On OF under "completed" I have 13 tasks that were completed yesterday. I removed the " - 1 * days" from the script and it also produces the same as above for today although I have completed 12 tasks.

Any idea what's wrong?

**Comment by svsmailus** [comment]
Ok, came down this morning and the script is working. Don't ask me why!

**Comment by stevelw** [comment]
I get a similar result with a Keyboard Maestro trigger if the script runs (on login) before OmniFocus has launched. 

Is Hazel running the script at a time OmniFocus isn't running?
