### ISSUE TITLE
Not creating file

### ISSUE THREAD

**Issue by keanders21** [joebuhlig/OFScripts#5]
I am attempting to use the code you wrote here and I can't get it to create the task report. I have a folder saved in my username folder called task reports, yet when I run the script I don't get any report.

**Comment by stevelw** [comment]
Just to check, did you edit the script to put in your actual account user name?

**Comment by keanders21** [comment]
Yeah I did, it acts like it's processing but when I go to the folder I have in the script, nothing is there

**Comment by stevelw** [comment]
Are you running the code from Hazel or through some other method?

If you are running in Hazel, try running just this part of the code and see if you get the file (but with no content):

```
on hazelProcessFile(theFile)
	set filePath to "/Users/USERNAME/TaskReports/" -- Where to save the resulting text file (Be sure to add the trailing "/")
	
	-- Create the new filename as YYYYMMDD.txt
	set todayDate to current date
	set yestDate to todayDate - 1 * days
	set {year:y, month:m, day:d} to yestDate
	set fileName to y * 10000
	set fileName to fileName + (m * 100)
	set fileName to fileName + d
	
	-- Set the starting date of the report
	set startDate to todayDate - 1 * days
	set startDate's hours to 0
	set startDate's minutes to 0
	set startDate's seconds to 0
	
	-- Set the ending date of the report
	set endDate to todayDate - 1 * days
	set endDate's hours to 23
	set endDate's minutes to 59
	set endDate's seconds to 59
	
	-- Create the blank report to build from
	set reportText to ""

-- Get the yesterday's date for the top of the report
			set runTime to date string of (todayDate - 1 * days)
			-- Add the date to the top of the report, enter down a couple lines, and add the report text
			set reportText to runTime & return & return & reportText
			-- Create the new report file
			set newFile to open for access filePath & fileName & ".txt" with write permission
			-- Add the report text to the new file
			write reportText to newFile
			-- Close the report file
			close access newFile
	
end hazelProcessFile
```

If you are running the script some other way not using Hazel, try removing the top and bottom lines:
`on hazelProcessFile(theFile)`
and
`end hazelProcessFile`

**Comment by keanders21** [comment]
Thanks, taking out the hazelProcessFile(theFile) lines got it to work running directly from omnifocus, however, I do want to use hazel.

Kevin E Anderson

**Comment by stevelw** [comment]
I'm not actually using Hazel at the moment (and have never used it with AppleScript), but I don't see any need for the two hazel lines (the one's you took out) when running from Hazel as you don't need to access a file Hazel hands you in this situation.

Can you take the code you just got working and put that into the Hazel rule?

**Comment by keanders21** [comment]
That worked, thank you very much for your help!

Kevin E Anderson

**Comment by stevelw** [comment]
Great. Are you able to raise a Pull request referencing this Issue (and leave the issue Open), with the fixed code?

**Comment by keanders21** [comment]
Yeah I am new to GitHub, let me figure out how to do that I will get it done.


Kevin E Anderson

**Comment by stevelw** [comment]
Do let me know if you need any pointers to getting started with GitHub/Git.

**Comment by joebuhlig** [comment]
I made some notes on this in the README for the Daily Task Report here: https://github.com/joebuhlig/OFScripts/commit/a941da97303561685c6c45d0f01c856908dfaa58

The `hazelProcessFile` handler is only for external scripts. I'm not sure if it works without at all. It's possible that it does if the file isn't required by the script. I just know that I have better luck with it included and run as an external script.

I'll close this as it seems you have it running correctly. Feel to open a new issue if you need further guidance.
