### ISSUE TITLE
Add Screenshot for Update Reviews Hazel Rule

### ISSUE THREAD

**Issue by stefanfrede** [joebuhlig/OFScripts#8]
Hi! Can you please add a screenshot of your Hazel rule how you trigger the Update Reviews script like you did for the Daily Task Report script? Thank you!

**Comment by stevelw** [comment]
You could use the same rule criteria for the Update Reviews script, or even run it in the same rule if you're using the Daily Report script.

**Comment by stefanfrede** [comment]
I'm using the same rule criteria but because nothing is happening I thought I did something wrong. This is why I asked for a screenshot.

**Comment by stevelw** [comment]
Could be same problem as #5 which relates to the task report script. 

Try running the non-Hazel version of the review script (still in Hazel) and see if that works. I think there must have been some change in the Hazel AppleScript dictionary or something.

**Comment by stefanfrede** [comment]
I just commented out the start and end onHazelProcessFile lines and that seemed to work, but those same lines seem to run without a problem in the Update Reviews script.

**Comment by joebuhlig** [comment]
I don't recommend running this from Hazel anymore. It's too easy to let projects go weeks without a review since the script will readjust them every day automatically from Hazel. It seems to be better to trigger it manually, as-needed with the non-Hazel version. 

Which method do you prefer to use? Hazel?

**Comment by stefanfrede** [comment]
Up until now I wasn't aware that a Hazel version existed and when I stumbled over it I thought it would be nice not to update it manually anymore. But now that you mention that there is a chance to miss reviews I guess I will stick to triggering it manually.
